//Staffs
export const STAFFS_ADD= 'STAFFS_ADD'
export const STAFFS_FAILED='STAFFS_FAILED'
export const STAFFS_LOADING ='STAFFS_LOADING'

export const STAFFS_PLUS= 'STAFFS_PLUS'
export const STAFFS_DELETE= 'STAFFS_DELETE'
export const STAFFS_UPDATE= 'STAFFS_UPDATE'

//Deparment
export const DEPARTMENTS_ADD ='DEPARTMENTS_ADD'
export const DEPARTMENTS_FAILED='DEPARTMENTS_FAILED'
export const DEPARTMENTS_LOADING ='DEPARTMENTS_LOADING'

// SalariesComponent
export const SALARIES_ADD ='SALARIES_ADD'
export const SALARIES_FAILED='SALARIES_FAILED'
export const SALARIES_LOADING ='SALARIES_LOADING'